### ISSUE TITLE
Deploy on Heroku 

### ISSUE THREAD

**Issue by zoredeaxx** [HirbodBehnam/file2url-go#1]
Can it be deployed on Heroku. Pl guide me in doing so. Where to put environment variables

**Comment by HirbodBehnam** [comment]
Hello
I'm not sure if you can deploy it on Heroku because you also need a config file present next to the executable. I will investigate if it's possible at last or not. (might need some changes in code)

**Comment by zoredeaxx** [comment]
Thanks for such a prompt and positive response and modifications of the code... Have been able to test the code.... It is working perfectly for media streaming.... but the download speed is very slow... Any fix for the same?

**Comment by HirbodBehnam** [comment]
Ok so that's good that it works! I haven't tested it myself and planned to test it today.
For the speed this looks like Heroku's problem because on my own server I get 4MB/s.

**Comment by zoredeaxx** [comment]
Okay... Unfortunately I am getting max speed of only 1 to 1.5 MB/s. Let us know of your results on Heroku.... Nevertheless thanks once again...

**Comment by zoredeaxx** [comment]
> Okay... Unfortunately I am getting max speed of only 1 to 1.5 MB/s. Let us know of your results on Heroku.... Nevertheless thanks once again...

**Comment by HirbodBehnam** [comment]
I tested it on a Europe dyno and the download speed was about 1.5MB/s from my server. I really doubt I can do anything to improve the speed for Heroku only. For normal server I can increase the buffer size but I don't really think anything can be done about Heroku.
