### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by zoredeaxx** [HirbodBehnam/file2url-go#2]
1. I increased the default partsize which resulted in enhanced download speed momentarily. However, the downloads are stopping abruptly in between. Can you please consider adding resume support functionality to avoid abrupt disconnection while downloading or have a look at the issue. Please suggest some solution... 

2.  Also if an inline url button can be included instead of plain reply text, it will give an asthetic appeal to the code.

**Comment by HirbodBehnam** [comment]
Hello
1. This is the reason I have choose a small part size because large part sizes causes the Telegram servers to rate limit you and thus halt the downloads in between.
2. I don't really know how does a inline button have advantage over a text link?

**Comment by zoredeaxx** [comment]
> Hello
> 
> 1. This is the reason I have choose a small part size because large part sizes causes the Telegram servers to rate limit you and thus halt the downloads in between.
> 2. I don't really know how does a inline button have advantage over a text link?

Hi, Thanks for the clarification but the download breaks with lower partsize as well... And regarding button, its just a cosmetic thing and doesn't enhance any functionality ...Not a major issue though..

**Comment by HirbodBehnam** [comment]
I haven't encountered such a problem. You mean download fails? or the speed goes up and down?
For the button I disagree. I, myself, want to see and copy the link.

**Comment by zoredeaxx** [comment]
> I haven't encountered such a problem. You mean download fails? or the speed goes up and down? For the button I disagree. I, myself, want to see and copy the link.

The speed increases/decreases depending on part size but Unfortunately the download fails randomly midway..The behaviour is same irrespective of part size.

Few logs as I get, if it could be of any help.... 

2022/02/16 15:43:38 cannot start client for download: rpcDoRequest: context canceled

2022/02/16 15:44:36 http: superfluous response.WriteHeader call from file2url/api.downloadEndpoint (api.go:45)

2022/02/16 15:44:36 cannot start client for download: rpcDoRequest: context canceled bytes=821035008-1042284543

**Comment by HirbodBehnam** [comment]
Context canceled means that the requester i.e. your computer has disconnected from the server. Are you using an application like IDM to download the files? That might be the reason for these logs.
For the speed decrease/increase I suspect that maybe requesting concurrent files from telegram from one client cause problems. I might later do some changes to create a new connection on each request. Maybe that helps.

**Comment by zoredeaxx** [comment]
> Context canceled means that the requester i.e. your computer has disconnected from the server. Are you using an application like IDM to download the files? That might be the reason for these logs. For the speed decrease/increase I suspect that maybe requesting concurrent files from telegram from one client cause problems. I might later do some changes to create a new connection on each request. Maybe that helps.

You are right. I tried IDM. If you can suggest any other softwares to download without interruptions, Will be greatful.. ... 
Thankyou for considering the request... Looking forward for the updates.

**Comment by HirbodBehnam** [comment]
I mainly use this application to download files from Telegram to my own server. So I use [aria2](https://github.com/aria2/aria2). But I will also try IDM and see how that performs with it and post the results later here.
